runtime: python
env: flex
entrypoint: gunicorn --limit-request-line 0 -b :$PORT main:app

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1
  
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10
